---
title: " Ensino Superior "
output: 
  flexdashboard::flex_dashboard:
    logo: figure/reconhecendosalvador.gif
    css: style.css
    social: menu
    orientation: columns
    vertical_layout: fill
    source_code: embed
---



```{r setup, include=FALSE}
library(flexdashboard)
#library(ggplot2)
library("DT")
library("readr")
library("dplyr")
library("ggplot2")
library("kableExtra")
library("tidyr")
library("formattable")
library("plotly")
library("ggplotlyExtra")
library("ggpubr")
library("tidyverse")
library("hrbrthemes")
library("waffle")
library(ggthemes)
library(extrafont)
library(gganimate)

CENSO_SUP <- NULL
CENSO_SUP <- read_delim("data/educacao/CENSO_SUPERIOR/DM_ALUNO_2009_2018_CO_IES_by_ANO_TP_COR_RACA_TP_SEXO.csv",",",escape_double = FALSE,trim_ws = FALSE)
#CENSO_SUP$TP_SEXO <- ifelse(CENSO_SUP$TP_SEXO==1,"Feminino","Masculino")
CENSO_SUP$TP_SEXO <- ifelse(CENSO_SUP$TP_SEXO==1,"F","M")

# Transformacao da variavel numerica de acordo com o vocabulario 
CENSO_SUP$TP_COR_RACA <- ifelse(CENSO_SUP$TP_COR_RACA==0,"*NQD",
                                CENSO_SUP$TP_COR_RACA <- ifelse(CENSO_SUP$TP_COR_RACA==1,"Branca",CENSO_SUP$TP_COR_RACA <- ifelse(CENSO_SUP$TP_COR_RACA==2,"Preta",CENSO_SUP$TP_COR_RACA <- ifelse(CENSO_SUP$TP_COR_RACA==3,"Parda",CENSO_SUP$TP_COR_RACA <- ifelse(CENSO_SUP$TP_COR_RACA==4,"Amarela",CENSO_SUP$TP_COR_RACA <- ifelse(CENSO_SUP$TP_COR_RACA==5,"Indígena",CENSO_SUP$TP_COR_RACA <- ifelse(CENSO_SUP$TP_COR_RACA==9,"*NDI",NA)))))))

CONCLUINTES_SSA <- CENSO_SUP %>% filter(IN_CONCLUINTE==1)



HEAT_SSA_IES_SEXO_RACA <- CONCLUINTES_SSA %>% dplyr::group_by(ANO_CENSO_SUP,TP_SEXO,TP_COR_RACA) %>% summarise(quantidade = sum(value,na.rm = "TRUE")) 


#target = c("Amarela","Branca","Indígena","Parda","Preta")
target = c("Parda","Preta")
HEAT_SSA_IES_SEXO_RACA_S_NQD_NDI <- HEAT_SSA_IES_SEXO_RACA %>%  filter(TP_COR_RACA %in% target) %>%
  dplyr::group_by(ANO_CENSO_SUP,TP_SEXO,TP_COR_RACA) %>% 
  summarise(quantidadef = sum(quantidade,na.rm = "TRUE")) 


```

Column {data-width=300}
-------------------------------------

O número de concluintes do sexo masculino (biológico - definição IBGE) 
e raça/cor (definição IBGE) preta está disponível no gráfico 
de barras ao lado. Enquanto a total de 
concluintes (2009-2019) desagregados por sexo 
são apresentados nos cartões abaixo.

### Concluintes do Sexo Feminino

```{r}
Sexo_Feminino <- CONCLUINTES_SSA %>% filter(TP_SEXO %in% c("F")) %>% summarise(valor=sum(value))
valueBox(Sexo_Feminino, icon = "fa-pencil",href="#concluintes-f",
         color = "#fac113")
```

### Concluintes do Sexo Masculino

```{r}
Sexo_Masculino <- CONCLUINTES_SSA %>% filter(TP_SEXO %in% c("M")) %>% summarise(valor=sum(value))
valueBox(Sexo_Masculino, icon = "fa-pencil", href="#concluintes-m")
```

### Total de Concluintes

```{r}
Total <- CONCLUINTES_SSA %>% summarise(valor=sum(value))
valueBox(Total, 
         icon = "fa-child",
         color = ifelse(Total > 3000000, "warning", "#db4470"))
```

Column {data-width=800}
-------------------------------------   

### <font size="5"> **Nº de concluintes em ensino superior - Sexo Masculino e Raça/Cor Preta** </font>

```{r, eval=TRUE, fig.height=4, fig.width=3}

objeto <- CONCLUINTES_SSA %>% filter(TP_COR_RACA %in% c("Preta")) %>% filter(TP_SEXO %in% c("M")) %>% group_by(ANO_CENSO_SUP) %>% summarise(value =sum(value)) %>%
ggplot(aes(x=ANO_CENSO_SUP,y=value)) +
  geom_bar(stat = "identity",fill="#00c4cc",color="#fac113") + 
  labs(
    title = "",
    x = "Ano",
    y = "Nº"
  ) +
  theme(title = element_text(size = 12,colour = "#db4470"))+
    theme(axis.title.x=element_text(size=22)) +
    theme(axis.title.y=element_text(size=22)) +
  theme(legend.text = element_text(size = 22)) +
    theme(axis.text = element_text(size = 22))  +
  theme(legend.position = "none")+
  theme(panel.grid = element_blank(), axis.ticks.y = element_line())+
#  theme( axis.line = element_line(colour = "darkblue", 
#                      size = 1, linetype = "solid"))+
  theme(panel.border = element_rect(fill=NA, color = "#64D2AA", size = 2))+
  theme(panel.background = element_rect(fill=NA,color = "gray70", size = 2),
        panel.grid.major = element_line(color = "gray70", size = .5),
        panel.grid.minor = element_line(color = "gray70", size = .25))
  
     #theme(plot.background = element_rect(fill = "#db4470"))
  
  #scale_color_ipsum() +
  #theme_ipsum_rc()
  #theme_minimal(base_family = "Roboto Condensed") +
  #theme(panel.grid = element_blank(), axis.ticks.y = element_line()) +
  #guides(fill = guide_legend(reverse = TRUE))
ggplotly(objeto)

```



